### PR TITLE
feat: Timestamps support

### LINKED ISSUE #150: Timestamps
I think, support for timestamps can be a great enhancment since it's a garden, and we want to see things grow.

To achieve that we can have following settings for maximum flexibility:
1. A global toggle to show or hide timestamps
2. 2 fields to select which keys to be used from the frontmatter for updated and created timestamps.

If the user choose to show the timestamps, we will first attempt to get the timestamps from the frontmatter, in that doesn't exist, then from file's created and updated dates.

### PR DESCRIPTION
**Pull request by uroybd**
This PR implements timestamps from frontmatter.

It adds the following settings:
1. How the timestamps will be formatted.
2. Show created
3. Created key
4. Show updated
5. Updated key

Closes #150 #140

### CODE REVIEW

**Comment by uroybd** [comment]
@oleeskild review it whenever you can.

I also found how to get the creation time and modification time from the Obsidian API. So, user can now fallback to those by keeping the key fields blank.

**Comment by uroybd** [comment]
@oleeskild any comment on this?

**Comment by Gonglja** [comment]
This is a very nice implementation. 

Some time ago, I was still troubled by the update status of the garden article, and I look forward to the author's cooperation

**Comment by oleeskild** [comment]
@uroybd Yep sorry for the wait, I haven't gotten around to looking at all the recent PRs yet. I'll try to look through them all this weekend.

**Comment by oleeskild** [comment]
Nicely done 🙌  It's great that you managed to retrieve the modified time and created time of the file to use as default. I imagine most people don't have an explicit created and updated frontmatter field.

**Comment by oleeskild** [comment]
I'll update the docs with the newly added features some time tomorrow.

**Pull request merged**
