### PR TITLE
path-rewrite support

### PR DESCRIPTION
**Pull request by uroybd**
Impements #157 

I've tested it on my digital garden. However, users should be warned I think.

Also, I haven't implemented `dg-path`. It will be resource-consuming to generate published note to the garden path with `dg-path`.

### CODE REVIEW

**Comment by oleeskild** [comment]
Hmm, I tested. it a bit, and it seems to be a bit wonky. For example, after publishing a note that had a rewrite applied, it shows up as deleted from vault in the publication center. I think it should be similar to what happens when moving a note. The new location for the note should now be under unpublished, and the old location should be under "Deleted from vault". 
CleanShot 2023-03-22 at 15 12 57

Although that could be confusing for users. We should perhaps show both the resolved path in the garden, and the vault path. Something like "* MyVaultPath/Note.md --> MyGardenPath/Note.md". And the note should just show up under changed, if a rewrite rule applies. I need to think about it a bit. Perhaps is time for an upgrade for the publication center view.

Do you have any thoughts on this?

**Comment by uroybd** [comment]
> Hmm, I tested. it a bit, and it seems to be a bit wonky. For example, after publishing a note that had a rewrite applied, it shows up as deleted from vault in the publication center. I think it should be similar to what happens when moving a note. The new location for the note should now be under unpublished, and the old location should be under "Deleted from vault". 
> CleanShot 2023-03-22 at 15 12 57
> 
> Although that could be confusing for users. We should perhaps show both the resolved path in the garden, and the vault path. Something like "* MyVaultPath/Note.md --> MyGardenPath/Note.md". And the note should just show up under changed, if a rewrite rule applies. I need to think about it a bit. Perhaps is time for an upgrade for the publication center view.
> 
> Do you have any thoughts on this?

I noticed this too. However, it happens for the first time and I deleted residues manually. It doesn't happen after that. It has something to do with sha mismatch.

**Comment by oleeskild** [comment]
> However, it happens for the first time and I deleted residues manually.
Ah, that explains why it disappeared with my testing as well.

**Comment by oleeskild** [comment]
I think there is an easier solution to this. We could still push the notes to the same location as before, but instead apply a dg-path to the frontmatter if a rewrite rule apply. Then people can also override the rewrite rule on single notes with that property. Then in the digital garden build we build the filetree with that info. We are already reading each file to get the permalink in the file tree. So it wouldn't add any big computation cost. Then we the "changed" part would work as expected, and we don't have to deal with the complexity of keeping track of which path to use etc. 

Thoughts?

**Comment by uroybd** [comment]
> I think there is an easier solution to this. We could still push the notes to the same location as before, but instead apply a dg-path to the frontmatter if a rewrite rule apply. Then people can also override the rewrite rule on single notes with that property. Then in the digital garden build we build the filetree with that info. We are already reading each file to get the permalink in the file tree. So it wouldn't add any big computation cost. Then we the "changed" part would work as expected, and we don't have to deal with the complexity of keeping track of which path to use etc. 
> 
> Thoughts?

That's a very good idea indeed! Let me implement this.

**Comment by uroybd** [comment]
@oleeskild Implemented it with just `dg-path` from plugin's end and rewrote the file tree generation in the template's part.

**Comment by Lisandra-dev** [comment]
Hello!
I tryed on my own blog, but the `dg-path` doesn't work at 100%. Some files work in the tree, other doesn't work

Website : https://digitalgarden-sooty.vercel.app/
repo : https://github.com/Lisandra-dev/digitalgarden/

**Comment by uroybd** [comment]
> Hello!
> I tryed on my own blog, but the `dg-path` doesn't work at 100%. Some files work in the tree, other doesn't work
> 
> Website : https://digitalgarden-sooty.vercel.app/
> repo : https://github.com/Lisandra-dev/digitalgarden/

Have you updated the template?

**Comment by uroybd** [comment]
@Lisandra-dev I've checked it out. It seems some of these files are added later manually instead of publishing from the plugin (The plugin puts JSON in the frontmatter). However, these should work too. Some of them are not showing in the file tree because `hide` is set to true. For others, links are not working, because the front-matter doesn't contain a permalink. Plugin always calculates and adds the permalink.

These are the two things I've noticed not working due to misconfiguration. Is there anything else? I would like to look at them too.

**Comment by Lisandra-dev** [comment]
I send the file using the plugin, so I don't understand why permalink and frontmatter are broken

**Comment by uroybd** [comment]
> I send the file using the plugin, so I don't understand why permalink and frontmatter are broken

That's Interesting. Which plugin version you're using? Compiled from my fork's path-rewrite branch?

@oleeskild can there be any reason the frontmatter is not JSON?

**Comment by Lisandra-dev** [comment]
Yes, I compiled from your path-rewrite branch !

**Comment by uroybd** [comment]
> Yes, I compiled from your path-rewrite branch !

I tried to reproduce the not-JSON frontmatter issue without any success. If you can, please let us know how to reproduce it.

**Comment by oleeskild** [comment]
> @oleeskild once you are satisfied with path rewrite, lets merge pinned notes and hide in graph too (pinned note and hide in graph goes hand in hand due to aesthetic reasons). We can have a very nice filetree-focused release. 😁

Good idea! I've merged them all in. About to do a release. I don't have time to write the docs for the features today. Hopefully I'll get to that tomorrow.

**Pull request merged**
