### PR TITLE
Transclude Block

### PR DESCRIPTION
**Pull request by uroybd**
This PR implements block transclusion as requested in this #137 

Along with that, it fixes a bug in header transculation.

In current logic, for this snippet:

```md
# Heading 1
## Heading 2
content

# Another heading 1
content more...
```
If I transclude by header, it will render just:

```md
# Heading 1
```
However, it should render:

```md
# Heading 1
## Heading 2
content
```

I've fixed that too.

### CODE REVIEW

**Comment by uroybd** [comment]
I did some work on generating block ID too (simple regex stuff). However, using markdown attributes will require the repo to include this plugin: https://www.npmjs.com/package/markdown-it-attrs

However, it will allow us to add the source to embed in all forms and the obsidian's embedding can be emulated vis-a-vis.

**Comment by oleeskild** [comment]
This is great! Thanks a bunch. I will look over the changes some time this week.

**Comment by uroybd** [comment]
> This is great! Thanks a bunch. I will look over the changes some time this week.

Cool. I've also successfully generated block attrs and linked them with embeds. Here's an example: http://localhost:8080/personal/musings/zen-poetry/

**Comment by oleeskild** [comment]
I've looked over the changes, and done some testing. Everything is working as expected. Merging it. Thanks for taking the time to create a Pull Request for this so everyone can benefit from your changes.

**Pull request merged**
