### PR TITLE
fix: 🐛 embed block reference appearence in transcluded text

### LINKED ISSUE #361: Block references appearence in transcluded text
This
image

Render this way (correctly) in `Obsidian` **1.3.5**
image

but renders this way in `Digital Garden` **2.45.2**
image

Is this the defect that was supposed to be solved or a different one?

_Originally posted by @SemanticBeeng in https://github.com/oleeskild/obsidian-digital-garden/issues/54#issuecomment-1666445942_

### PR DESCRIPTION
**Pull request by uroybd**
Closes #361

### CODE REVIEW

**Comment by uroybd** [comment]
@oleeskild Hope you are well. Review this and the previous bug-fix PR whenever you can.

**Comment by SemanticBeeng** [comment]
Thank you, looking forward to fix.

Checking: is `Digital Garden` supposed to provide full ``[[embed links[[` support?
 *  `![[embed link#heading]]`
 * `![[embed link#^blockId]]`

See issues with rendering described here: https://github.com/orgs/ObsidianPublisher/discussions/190#discussioncomment-6678475

**Comment by uroybd** [comment]
> Thank you, looking forward to fix.
> 
> Checking: is `Digital Garden` supposed to provide full `[[embed links]]` support?
>  *  `![[embed link#heading]]`
>  * `![[embed link#^blockId]]`
> 
> See issues with rendering described here: https://github.com/orgs/ObsidianPublisher/discussions/190#discussioncomment-6678475 

It supports images, excalidraw, and text transculsion now. Can easily add video though. I'm also planning to work on Canvas whenever I can. But, beyond that, I'm not sure. We can try to make it dynamic enough to allow 11ty handle it based on user-provided scripts.

**Comment by SemanticBeeng** [comment]
To clarify my ask above. those types of embed links are Obsidian proper.
The ask is to support them at time of publish as well.

I think this is critical because they whole point of Obsidian is to create `atomic notes`.
But this leads to more fine grained embeds/transclusions.

At this time there is no OSS support for these in "publish".

**Comment by uroybd** [comment]
Hi @oleeskild

Tend to it whenever you can. I hope you're well.

**Comment by oleeskild** [comment]
Hi @uroybd 
Thanks for the concern! I'm very well. The reason you haven't heard from me is that I've recently moved to Italy where I will be living for the next months. All my free time besides work has been tied up in getting things ready for that. I've been feeling bad for not responding to anything here, but I simply haven't gotten around to look at it.  

I will take a look at this PR, and hopefully all the others, next week. This week is still very busy, with a lot of stuff to do. But next week I'll finally have some time to look at this. Thanks for the patience 🙏!

**Comment by uroybd** [comment]
> Hi @uroybd Thanks for the concern! I'm very well. The reason you haven't heard from me is that I've recently moved to Italy where I will be living for the next months. All my free time besides work has been tied up in getting things ready for that. I've been feeling bad for not responding to anything here, but I simply haven't gotten around to look at it.
> 
> I will take a look at this PR, and hopefully all the others, next week. This week is still very busy, with a lot of stuff to do. But next week I'll finally have some time to look at this. Thanks for the patience 🙏!

Have a nice time in Italy! Glad to know you are well. (Interactions in Github are kind of unique. We connect like professionals while working on some labor of passion. It worked well for me until the COVID-19. I've seen so many people simply vanish that their well-being comes to the top of my mind before everything now.)

Review them whenever you can. Take care.

**Comment by oleeskild** [comment]
Looks good! Thanks for fixing it 🎉

**Pull request merged**
